# Generated by Django 3.1.13 on 2021-09-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_localize_rws_languagecloud", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="languagecloudproject",
            name="internal_status",
            field=models.CharField(
                choices=[("new", "new"), ("imported", "imported")],
                default="new",
                max_length=255,
            ),
        ),
    ]
