# Generated by Django 3.1.13 on 2021-11-24 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_localize_rws_languagecloud", "0004_auto_20211118_1013"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="languagecloudfile",
            options={"ordering": ["-project__source_last_updated_at"]},
        ),
        migrations.AlterModelOptions(
            name="languagecloudproject",
            options={"ordering": ["-source_last_updated_at"]},
        ),
    ]
