# Generated by Django 3.1.14 on 2022-05-06 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_localize_rws_languagecloud", "0005_languagecloudprojectsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="languagecloudfile",
            name="revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="wagtailcore.pagerevision",
            ),
        ),
    ]
