name: Localize RWS LanguageCloud CI

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - uses: pre-commit/action@v3.0.0

  test-sqlite:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.8', '3.9', '3.10']
        django-wagtail:
          - 'django3.2-wagtail2.15'
          - 'django3.2-wagtail3.0'
          - 'django3.2-wagtail4.0'
          - 'django3.2-wagtail4.1'
          - 'django3.2-wagtail4.2'
          - 'django4.1-wagtail4.0'
          - 'django4.1-wagtail4.1'
          - 'django4.1-wagtail4.2'
        include:
          - python: '3.11'
            django-wagtail: 'django4.1-wagtail4.1'
          - python: '3.7'
            django-wagtail: 'django3.2-wagtail4.1'
          - python: '3.7'
            django-wagtail: 'django3.2-wagtail4.2'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox
        run: |
          python -m pip install tox
      - name: Test
        run: |
          tox
        env:
          TOXENV: python${{ matrix.python }}-${{ matrix.django-wagtail }}-sqlite

  test-postgres:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.8', '3.9', '3.10']
        django-wagtail:
          - 'django3.2-wagtail2.15'
          - 'django3.2-wagtail3.0'
          - 'django3.2-wagtail4.0'
          - 'django3.2-wagtail4.1'
          - 'django3.2-wagtail4.2'
          - 'django4.1-wagtail4.0'
          - 'django4.1-wagtail4.1'
          - 'django4.1-wagtail4.2'
        include:
          - python: '3.11'
            django-wagtail: 'django4.1-wagtail4.1'

    services:
      postgres:
        image: postgres:12.7
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox
        run: |
          python -m pip install tox
      - name: Test
        run: |
          tox
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/wagtail_localize_rws_languagecloud
          TOXENV: python${{ matrix.python }}-${{ matrix.django-wagtail }}-postgres
