name: Localize RWS LanguageCloud CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Tox
        run: |
          python -m pip install tox
      - name: Lint
        run: tox
        env:
          TOXENV: lint

  test-sqlite:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        'python': ['3.7', '3.8', '3.9']
        'django-wagtail':
          - 'django2.2-wagtail2.11'
          - 'django3.1-wagtail2.11'
          - 'django3.1-wagtail2.14'
          - 'django3.2-wagtail2.14'
          - 'django3.2-wagtail2.15'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox
        run: |
          python -m pip install tox
      - name: Test
        run: |
          tox
        env:
          TOXENV: python${{ matrix.python }}-${{ matrix.django-wagtail }}-sqlite

  test-postgres:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        postgres: ['10.8']
        'python': ['3.7', '3.8', '3.9']
        'django-wagtail':
          - 'django2.2-wagtail2.11'
          - 'django3.1-wagtail2.11'
          - 'django3.1-wagtail2.14'
          - 'django3.2-wagtail2.14'
          - 'django3.2-wagtail2.15'

    services:
      postgres:
        image: postgres:${{ matrix.postgres }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox
        run: |
          python -m pip install tox
      - name: Test
        run: |
          tox
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/wagtail_localize_rws_languagecloud
          TOXENV: python${{ matrix.python }}-${{ matrix.django-wagtail }}-postgres
