name: Localize RWS LanguageCloud CI

on:
  push:
    branches:
      - main
      - master
      - 'stable/**'

  pull_request:

jobs:
  test-sqlite:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        'python': ['3.7', '3.8', '3.9']
        'django-wagtail':
          - 'django2.2-wagtail2.11'
          - 'django3.1-wagtail2.11'
          - 'django3.1-wagtail2.14'
          - 'django3.2-wagtail2.14'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox
        run: |
          python -m pip install tox
      - name: Test
        run: |
          tox
        env:
          TOXENV: python${{ matrix.python }}-${{ matrix.django-wagtail }}-sqlite

  test-postgres:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        postgres: ['10.8']
        'python': ['3.7', '3.8', '3.9']
        'django-wagtail':
          - 'django2.2-wagtail2.11'
          - 'django3.1-wagtail2.11'
          - 'django3.1-wagtail2.14'
          - 'django3.2-wagtail2.14'

    services:
      postgres:
        image: postgres:${{ matrix.postgres }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox
        run: |
          python -m pip install tox
      - name: Test
        run: |
          tox
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/wagtail_localize_rws_languagecloud
          TOXENV: python${{ matrix.python }}-${{ matrix.django-wagtail }}-postgres
